on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          cargo-pakages: cargo-bloat
      - name: Run cargo bloat
        run: cargo bloat
