on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo bloat
        uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: cargo-bloat
      - name: Run cargo bloat
        run: cargo bloat
      #- name: Run cargo bloat
        #uses: orf/cargo-bloat-action@v1
        #with:
          #token: ${{ secrets.GITHUB_TOKEN }}
